export enum PrivateKeyEnum {
  ACCESS_PRI_TOEKN = 'ACCESS_PRI_TOEKN',
  REFRESH_PRI_TOKEN = 'REFRESH_PRI_TOKEN',
}

export enum PublicKeyEnum {
  ACCESS_PUBLIC_TOKEN = 'ACCESS_PUBLIC_TOKEN',
  REFRESH_PUBLIC_TOKEN = 'REFRESH_PUBLIC_TOKEN',
}
